Pytorch --> It is a framework/library for DL and it is use for making Neural Network , train the DL model , Computer vision , NLP , AI Application

Simple Flow

Data -- Tensor -- Prediction -- Loss -- Backpropagation -- Wt. Update

In [20]:
import torch

In [21]:
print(torch.__version__)

2.12.0+cpu


Tensor --> Adv. DL version of Numpy array

In [22]:
import torch

x=torch.tensor([10,20,30])
x

tensor([10, 20, 30])

In [23]:
x.shape

torch.Size([3])

In [24]:
#scalar
scalar=torch.tensor(10)

#vector
vector=torch.tensor([1,2,3])

#matrix
matrix=torch.tensor([[1,2,3],
                     [4,5,6]])

print("Scalar :",scalar)
print("Vector :",vector)
print("Matrix :\n",matrix)

Scalar : tensor(10)
Vector : tensor([1, 2, 3])
Matrix :
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [25]:
x=torch.tensor([[1,2,3],
                [4,5,6]])
print("Tensor :\n",x)

print("Shape :",x.shape)
print("Dimension :",x.ndim)


Tensor :
 tensor([[1, 2, 3],
        [4, 5, 6]])
Shape : torch.Size([2, 3])
Dimension : 2


In [26]:
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])

print("Addition :",x+y)
print("Multiplication :",x*y)

Addition : tensor([5, 7, 9])
Multiplication : tensor([ 4, 10, 18])


In [27]:
A=torch.tensor([[1,2,3],
                [4,5,6]])
B=torch.tensor([[1,2],
                [4,5],
                [2,4]])
print("Matrix Multiplication :\n",A.matmul(B))

Matrix Multiplication :
 tensor([[15, 24],
        [36, 57]])


Broadcasting ----> it means to do operation on different different shape of tensor

In [29]:
x=torch.tensor([[1,2,3],
               [4,5,6]])
y=torch.tensor([10,20,30])

print("Add :\n",x+y)

Add :
 tensor([[11, 22, 33],
        [14, 25, 36]])


In [ ]:
x=torch.tensor([1,2,3,4,5,6])
print("Reshape :\n",x.reshape(2,3))   #reshape --> shape change

print("Vieew :\n",x.view(2,3))

Reshape :
 tensor([[1, 2, 3],
        [4, 5, 6]])
Vieew :
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
x=torch.tensor([1,2,3,4,5,6])
print("Shape of x : ",x.shape)
y=x.unsqueeze(0)                #unsqueeze --> dimension add
print("Shape of y : ",y.shape)

Shape of x :  torch.Size([6])
Shape of y :  torch.Size([1, 6])


In [ ]:
x=torch.tensor([[1,2,3,4,5,6]])
print("Shape of x : ",x.shape)
y=x.squeeze()                  #squeeze ---> size-1 dimension removed
print("Shape of y : ",y.shape)

Shape of x :  torch.Size([1, 6])
Shape of y :  torch.Size([6])


Gradient batata hai ki kisi value ko thoda change karne par output kitna aur kis direction mein change hoga.

PyTorch Autograd --> Automatically calculate gradient

In [46]:
import torch
x = torch.tensor(2.0, requires_grad=True)  #It tell us that --- PyTorch, x ke saath hone wale calculations ko track karo, kyunki mujhe iska gradient calculate karna hai
y = x ** 2
y.backward()
print(x.grad)

tensor(4.)


In [47]:
weight = torch.tensor(2.0, requires_grad=True)
prediction = weight * 3
loss = (prediction - 10) ** 2
loss.backward()
print(weight.grad)

tensor(-24.)
