Pytorch --> It is a framework/library for DL and it is use for making Neural Network , train the DL model , Computer vision , NLP , AI Application

Simple Flow

Data -- Tensor -- Prediction -- Loss -- Backpropagation -- Wt. Update

In [25]:
import torch

In [26]:
print(torch.__version__)

2.12.0+cpu


Tensor --> Adv. DL version of Numpy array

In [27]:
import torch

x=torch.tensor([10,20,30])
x

tensor([10, 20, 30])

In [28]:
x.shape

torch.Size([3])

In [29]:
#scalar
scalar=torch.tensor(10)

#vector
vector=torch.tensor([1,2,3])

#matrix
matrix=torch.tensor([[1,2,3],
                     [4,5,6]])

print("Scalar :",scalar)
print("Vector :",vector)
print("Matrix :\n",matrix)

Scalar : tensor(10)
Vector : tensor([1, 2, 3])
Matrix :
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [30]:
x=torch.tensor([[1,2,3],
                [4,5,6]])
print("Tensor :\n",x)

print("Shape :",x.shape)
print("Dimension :",x.ndim)


Tensor :
 tensor([[1, 2, 3],
        [4, 5, 6]])
Shape : torch.Size([2, 3])
Dimension : 2


In [31]:
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])

print("Addition :",x+y)
print("Multiplication :",x*y)

Addition : tensor([5, 7, 9])
Multiplication : tensor([ 4, 10, 18])


In [32]:
A=torch.tensor([[1,2,3],
                [4,5,6]])
B=torch.tensor([[1,2],
                [4,5],
                [2,4]])
print("Matrix Multiplication :\n",A.matmul(B))

Matrix Multiplication :
 tensor([[15, 24],
        [36, 57]])


Broadcasting ----> it means to do operation on different different shape of tensor

In [33]:
x=torch.tensor([[1,2,3],
               [4,5,6]])
y=torch.tensor([10,20,30])

print("Add :\n",x+y)

Add :
 tensor([[11, 22, 33],
        [14, 25, 36]])


In [34]:
x=torch.tensor([1,2,3,4,5,6])
print("Reshape :\n",x.reshape(2,3))   #reshape --> shape change

print("Vieew :\n",x.view(2,3))

Reshape :
 tensor([[1, 2, 3],
        [4, 5, 6]])
Vieew :
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [35]:
x=torch.tensor([1,2,3,4,5,6])
print("Shape of x : ",x.shape)
y=x.unsqueeze(0)                #unsqueeze --> dimension add
print("Shape of y : ",y.shape)

Shape of x :  torch.Size([6])
Shape of y :  torch.Size([1, 6])


In [36]:
x=torch.tensor([[1,2,3,4,5,6]])
print("Shape of x : ",x.shape)
y=x.squeeze()                  #squeeze ---> size-1 dimension removed
print("Shape of y : ",y.shape)

Shape of x :  torch.Size([1, 6])
Shape of y :  torch.Size([6])


Gradient batata hai ki kisi value ko thoda change karne par output kitna aur kis direction mein change hoga.

PyTorch Autograd --> Automatically calculate gradient

In [37]:
import torch
x = torch.tensor(2.0, requires_grad=True)  #It tell us that --- PyTorch, x ke saath hone wale calculations ko track karo, kyunki mujhe iska gradient calculate karna hai
y = x ** 2
y.backward()
print(x.grad)

tensor(4.)


In [38]:
weight = torch.tensor(2.0, requires_grad=True)
prediction = weight * 3
loss = (prediction - 10) ** 2
loss.backward()
print(weight.grad)

tensor(-24.)


In [39]:
import torch
# Weight
w = torch.tensor(5.0, requires_grad=True)
# Learning rate
learning_rate = 0.1
# Input
x = torch.tensor(2.0)
# Actual output
y_true = torch.tensor(4.0)
# Training
for epoch in range(10):
    # Forward pass
    y_pred = w * x
    # Loss
    loss = (y_pred - y_true) ** 2
    # Backpropagation
    loss.backward()
    # Weight update
    with torch.no_grad():
        w -= learning_rate * w.grad
    # Gradient reset
    w.grad.zero_()
    print(
        "Epoch:", epoch + 1,
        "Loss:", loss.item(),
        "Weight:", w.item()
    )

Epoch: 1 Loss: 36.0 Weight: 2.5999999046325684
Epoch: 2 Loss: 1.4399995803833008 Weight: 2.119999885559082
Epoch: 3 Loss: 0.05759989097714424 Weight: 2.0239999294281006
Epoch: 4 Loss: 0.002303986344486475 Weight: 2.0048000812530518
Epoch: 5 Loss: 9.216312173521146e-05 Weight: 2.000960111618042
Epoch: 6 Loss: 3.687257276396849e-06 Weight: 2.0001919269561768
Epoch: 7 Loss: 1.4734382602910046e-07 Weight: 2.0000383853912354
Epoch: 8 Loss: 5.893753041164018e-09 Weight: 2.0000076293945312
Epoch: 9 Loss: 2.3283064365386963e-10 Weight: 2.0000014305114746
Epoch: 10 Loss: 8.185452315956354e-12 Weight: 2.000000238418579


Neural Network   ----> Single Neuron Network

In [40]:
import torch 
import torch.nn as nn
import torch.optim as optim


In [41]:
# 1 ---> Datasets
x=torch.tensor([[1.0],[2.0],[3.0],[4.0]])
y=torch.tensor([[2.0],[4.0],[6.0],[8.0]])

# 2 --> Create model
model = nn.Linear(1,1)

# 3 ---> Loss Function
loss_function = nn.MSELoss()

# 4 ---> Optimizer
optimizer = optim.SGD(
    model.parameters(),
    lr=0.01
)

# 5 ---> Training loop
for epoch in range(100):
    # Forward pass
    y_pred=model(x)

    #Loss
    loss=loss_function(y_pred,y)

    #remove old gradient
    optimizer.zero_grad()

    # Backward propagation
    loss.backward()

    # Update weight and bias
    optimizer.step()

    #print loss in every  10 step
    if (epoch + 1) % 10 == 0:
        print(
            f"epoch{epoch + 1} , "
            f"Loss : {loss.item():.4f}"
        )

# 6 ---> Prediction
with torch.no_grad():
    test = torch.tensor([[5.0]])
    prediction=model(test)
    print("Prediction for x=5.0 :",prediction.item())
    

epoch10 , Loss : 2.5571
epoch20 , Loss : 0.1594
epoch30 , Loss : 0.0920
epoch40 , Loss : 0.0851
epoch50 , Loss : 0.0801
epoch60 , Loss : 0.0754
epoch70 , Loss : 0.0710
epoch80 , Loss : 0.0669
epoch90 , Loss : 0.0630
epoch100 , Loss : 0.0594
Prediction for x=5.0 : 9.583599090576172
